<a href="https://colab.research.google.com/github/HalyshAnton/IT-Step-Pyton-AI/blob/main/module2/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [31]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [32]:
a = np.arange(30,70,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [33]:
b = np.linspace(0,0.9,10)
print(b)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [34]:
def increase_size(array: np.array, size: int):
    return np.pad(array, ((0, size), (0, size)), 'constant', constant_values=0)

    
a = np.ones((5,1))
print(a.shape)
print(a)
b = increase_size(a,2)
print(b.shape)
print(b)

(5, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(7, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [35]:
print(a.dtype)
a = a.astype(int)
print(a.dtype)

float64
int64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [44]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
print(x<var)
x[x<var] -= 1
print(x)


[ True False  True False False False False  True]
[0 5 2 8 6 5 7 3]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [52]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

print(X)
filter = np.isnan(X)
X[filter]= -1
print(X)

[[ 1.  2. nan  4.]
 [ 5. nan nan  4.]
 [nan 10. 11. nan]]
[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [60]:
q = np.random.random((4,6))
print(q)
q = q.reshape(3,8)
print(q)

[[0.56523861 0.30797768 0.25354313 0.04313661 0.1509924  0.6018124 ]
 [0.77247446 0.59896875 0.27538521 0.60048008 0.76275931 0.43916947]
 [0.11096128 0.36185304 0.02689574 0.20092446 0.71881553 0.87778371]
 [0.44059972 0.60662869 0.17736259 0.31835328 0.8501023  0.53766626]]
[[0.56523861 0.30797768 0.25354313 0.04313661 0.1509924  0.6018124
  0.77247446 0.59896875]
 [0.27538521 0.60048008 0.76275931 0.43916947 0.11096128 0.36185304
  0.02689574 0.20092446]
 [0.71881553 0.87778371 0.44059972 0.60662869 0.17736259 0.31835328
  0.8501023  0.53766626]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [63]:
w = np.random.random((3,4))
print(w.mean(axis=0))

[0.59096578 0.26400839 0.14454485 0.66099596]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [102]:
e = np.random.random((5,6))
e = e.round(1)
print(e)
sorted = np.argsort(e[0,:])
print("\n", sorted)
e_sorted = e[:, sorted]
print("\n",e_sorted)


[[0.9 0.8 0.1 0.1 0.6 0. ]
 [0.8 0.5 0.4 0.  1.  0.7]
 [0.6 0.4 0.4 0.1 0.3 0.7]
 [0.8 0.9 0.5 1.  0.7 0.6]
 [0.9 0.4 0.7 0.3 0.8 0.1]]

 [5 2 3 4 1 0]

 [[0.  0.1 0.1 0.6 0.8 0.9]
 [0.7 0.4 0.  1.  0.5 0.8]
 [0.7 0.4 0.1 0.3 0.4 0.6]
 [0.6 0.5 1.  0.7 0.9 0.8]
 [0.1 0.7 0.3 0.8 0.4 0.9]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [109]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

filter = np.logical_and(X>3, X<6)
print(X[filter])

[4 5 5 4]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом.

Після цього всі значення мають бути в межах [0, 1]

In [116]:
t = np.random.random((5,6))*100
print("\n", t)
# t_col_min = t.min(axis=0)
# t_col_max = t.max(axis=0)
t_min = t.min()
t_max = t.max()
print("\n", t_min)
print("\n", t_max)

t -= t_min
print("\n", t)
t /= (t_max-t_min)
print("\n", t)






 [[23.81523044 56.01499384 85.5200214  93.18361136 89.26202043 11.90407098]
 [14.2598712  71.61812832 20.03956906 33.86499711 37.49557924 13.36764951]
 [ 2.72430836 92.45426548 61.54027716 73.92525776 71.0460956  71.10064626]
 [95.78576736 84.47827252 47.28404666 72.1131342  85.79758549 36.45282329]
 [81.0773297  62.65125654 16.79262789 84.25225046 96.33417671 68.3277912 ]]

 2.7243083580638983

 96.33417671465998

 [[21.09092208 53.29068548 82.79571304 90.459303   86.53771208  9.17976262]
 [11.53556284 68.89381996 17.3152607  31.14068875 34.77127088 10.64334115]
 [ 0.         89.72995712 58.8159688  71.20094941 68.32178724 68.3763379 ]
 [93.061459   81.75396416 44.5597383  69.38882584 83.07327714 33.72851493]
 [78.35302135 59.92694818 14.06831954 81.5279421  93.60986836 65.60348284]]

 [[0.22530661 0.56928491 0.88447633 0.96634366 0.92445074 0.09806405]
 [0.1232302  0.73596749 0.1849726  0.33266459 0.37144877 0.11369892]
 [0.         0.95855233 0.62830949 0.76061371 0.72985667 0.7304