<a href="https://colab.research.google.com/github/HalyshAnton/IT-Step-Pyton-AI/blob/main/module2/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [2]:
a = np.arange(1,13)
print(a)
print(type(a.dtype))
print(a.shape)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.dtypes.Int64DType'>
(12,)


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [3]:
a = a.reshape(3, 4)
print(a)
a = a.astype(float)
print(a.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
float64


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [4]:
x = np.zeros((8,8), dtype=int)
print(x)
x[::2, ::2] = 1
x[1::2, 1::2] = 1
print(x)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [5]:
rand = np.random.random((4,3))
print(rand)

print(rand.sum(axis=0))
print(rand.sum(axis=1))
print(rand.sum())

[[0.65698539 0.50170736 0.32843181]
 [0.35589209 0.36255461 0.89173461]
 [0.59400971 0.45881796 0.40038976]
 [0.73733964 0.20255216 0.95853084]]
[2.34422684 1.52563209 2.57908702]
[1.48712456 1.61018132 1.45321743 1.89842264]
6.4489459457480764


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [6]:
print(rand)
print(rand.max(axis=1))
print(rand-rand.max(axis=1,keepdims=True))


[[0.65698539 0.50170736 0.32843181]
 [0.35589209 0.36255461 0.89173461]
 [0.59400971 0.45881796 0.40038976]
 [0.73733964 0.20255216 0.95853084]]
[0.65698539 0.89173461 0.59400971 0.95853084]
[[ 0.         -0.15527804 -0.32855358]
 [-0.53584252 -0.52918     0.        ]
 [ 0.         -0.13519175 -0.19361996]
 [-0.22119119 -0.75597867  0.        ]]


# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

In [7]:
mass_matrix = np.array([5,10,25,40])
ship_content = np.array([20,5,10,4])
print(ship_content @ mass_matrix)

560


# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.

In [8]:
ship_contents = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(ship_contents @ mass_matrix)

[260 580 900]
